# Generated by Django 4.2.4 on 2023-10-26 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0001_initial"),
        ("users", "0003_alter_user_phone_number_verificationcode"),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("Direktor", "Director"),
                            ("Xisobchi", "Accountant"),
                            ("Menejer", "Manager"),
                            ("Kassir", "Cashier"),
                            ("Dasturchi", "Developer"),
                            ("Moderator", "Moderator"),
                            ("Ishchi", "Employee"),
                        ],
                        max_length=64,
                    ),
                ),
                ("salary", models.PositiveIntegerField()),
                ("date_out", models.DateField(blank=True, null=True)),
                ("date_in", models.DateField(blank=True, null=True)),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_station",
                        to="stations.station",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
