# Generated by Django 4.2.4 on 2023-10-26 20:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_employee"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(
                choices=[
                    ("Direktor", "Director"),
                    ("Xisobchi", "Accountant"),
                    ("Menejer", "Manager"),
                    ("Kassir", "Cashier"),
                    ("dasturchi", "DEVELOPER"),
                    ("Moderator", "Moderator"),
                    ("Ishchi", "Employee"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 12 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
    ]
