# Generated by Django 4.2.4 on 2023-10-27 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_employee_position_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="position",
            field=models.CharField(
                choices=[
                    ("director", "DIRECTOR"),
                    ("accountant", "ACCOUNTANT"),
                    ("manager", "MANAGER"),
                    ("cashier", "CASHIER"),
                    ("developer", "DEVELOPER"),
                    ("moderator", "MODERATOR"),
                    ("employee", "EMPLOYEE"),
                ],
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, null=True),
        ),
    ]
