# Generated by Django 4.2.4 on 2023-10-31 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0002_dailyreport"),
        ("users", "0006_alter_employee_position_alter_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="station",
        ),
        migrations.AlterField(
            model_name="employee",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_user",
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="employee",
            name="station",
            field=models.ManyToManyField(
                related_name="user_station", to="stations.station"
            ),
        ),
    ]
