# Generated by Django 4.2.4 on 2023-10-31 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_remove_employee_station_alter_employee_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employee_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
