# Generated by Django 4.2.4 on 2023-10-26 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Xumo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("amount_of_money", models.PositiveIntegerField()),
                (
                    "picture_of_bill",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                ("date", models.DateField()),
                (
                    "station",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="station_xumocard",
                        to="stations.station",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xumo",
                "verbose_name_plural": "Xumo kartalari",
                "ordering": ["date"],
                "unique_together": {("station", "date")},
            },
        ),
        migrations.CreateModel(
            name="UzCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("amount_of_money", models.PositiveIntegerField()),
                (
                    "picture_of_bill",
                    models.FileField(blank=True, null=True, upload_to=""),
                ),
                ("date", models.DateField()),
                (
                    "station",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="station_uzcard",
                        to="stations.station",
                    ),
                ),
            ],
            options={
                "verbose_name": "Uzcard",
                "verbose_name_plural": "Uzcard kartalari",
                "ordering": ["date"],
                "unique_together": {("station", "date")},
            },
        ),
    ]
