# Generated by Django 4.2.4 on 2023-10-26 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
        ("companies", "0002_dailreportofallcompany"),
        ("users", "0004_employee"),
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "counter_amount_of_gas",
                    models.FloatField(
                        help_text="Hisoblagichdagi ko'rsatilgan gaz miqdori."
                    ),
                ),
                (
                    "loss_of_gas",
                    models.FloatField(default=1.2, help_text="Yo'qotilgan gaz foizda."),
                ),
                ("gas_price", models.PositiveIntegerField(default=3250)),
                (
                    "cash",
                    models.FloatField(
                        default=0, help_text="Naqtga sotilgan gas qiymati."
                    ),
                ),
                (
                    "profit",
                    models.IntegerField(
                        default=0, help_text="Naqtga sotilgan gas qiymati summasi."
                    ),
                ),
                ("date_of_daily_report", models.DateField()),
                (
                    "daily_report_of_company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_report_all_company",
                        to="companies.dailreportofallcompany",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="report_user",
                        to="users.employee",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="station",
                        to="stations.station",
                    ),
                ),
                (
                    "uzcard",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_report_uzcard",
                        to="common.uzcard",
                    ),
                ),
                (
                    "xumo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="daily_report_xumo",
                        to="common.xumo",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
