# Generated by Django 4.2.4 on 2023-10-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0002_dailyreport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreport",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="dailyreport",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="station",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
