# Generated by Django 4.2.4 on 2023-11-01 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0004_expense"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="station",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="station_expense",
                to="stations.station",
            ),
        ),
        migrations.CreateModel(
            name="Collector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gas_quantity_from_gres", models.FloatField()),
                ("date", models.DateField()),
                ("profit", models.FloatField()),
                ("station", models.ManyToManyField(to="stations.station")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
