# Generated by Django 4.2.4 on 2023-11-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0005_alter_expense_station_collector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="collector",
            name="profit",
            field=models.FloatField(default=1),
        ),
    ]
