# Generated by Django 4.2.4 on 2023-10-26 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_employee"),
        ("companies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailReportOfAllCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("gas_quantity", models.FloatField(default=0)),
                ("date", models.DateField(unique=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="all_company_report_employee",
                        to="users.employee",
                    ),
                ),
            ],
            options={
                "unique_together": {("date", "employee")},
            },
        ),
    ]
