# Generated by Django 4.2.4 on 2023-10-26 17:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0002_dailreportofallcompany"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="employees",
            new_name="drivers",
        ),
    ]
