# Generated by Django 4.2.4 on 2023-10-31 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("companies", "0005_alter_company_contact_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="company",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="dailreportofallcompany",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="dailreportofallcompany",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="drivegasusage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="drivegasusage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="driver",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="driver",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
