# Generated by Django 4.2.4 on 2023-10-31 13:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("stations", "0003_alter_dailyreport_created_at_and_more"),
        (
            "companies",
            "0006_alter_company_created_at_alter_company_updated_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="drivegasusage",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="driver_station",
                to="stations.station",
            ),
        ),
        migrations.AlterField(
            model_name="driver",
            name="phone_number",
            field=models.CharField(
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 12 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
    ]
